# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'SkeletonTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'TABAnimated', '~> 2.2.5'
pod 'Masonry', '~> 1.1.0'
  # Pods for SkeletonTest

end
