# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'LikeOrNotLike' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'ZLSwipeableView', '~> 0.0.8'
pod 'TABCardView', '~> 0.0.1'
  # Pods for LikeOrNotLike
pod 'Masonry', '~> 1.1.0'
pod 'SDWebImage', '~> 5.7.2'
end
